#!/usr/bin/env python3
"""Read logup_sweep JSON lines from stdin, emit chunk_table.rs to stdout.

Usage:
    cargo run --release --bin logup_sweep | python3 scripts/logup_codegen.py \
        > rust/jstprove_circuits/src/circuit_functions/gadgets/chunk_table.rs
"""
import json
import sys
from collections import defaultdict

ELEMENT_BUCKETS = [10_000, 50_000, 100_000, 500_000, 0xFFFF_FFFF]
BUCKET_LABELS = ["10_000", "50_000", "100_000", "500_000", "u32::MAX"]


def main():
    records = []
    for line in sys.stdin:
        line = line.strip()
        if not line or not line.startswith("{"):
            continue
        records.append(json.loads(line))

    if not records:
        print("no records on stdin", file=sys.stderr)
        sys.exit(1)

    # Group by (kappa, model) → list of (chunk_bits, circuit_bytes)
    by_model = defaultdict(list)
    for r in records:
        key = (r["kappa"], r["model"])
        by_model[key].append((r["chunk_bits"], r["circuit_bytes"]))

    # For each (kappa, model), find the chunk_bits with smallest circuit
    best_by_kappa = defaultdict(list)
    for (kappa, model), results in by_model.items():
        best_chunk = min(results, key=lambda x: x[1])[0]
        best_by_kappa[kappa].append(best_chunk)

    # For each kappa, pick the most common winner across models
    optimal = {}
    for kappa, winners in best_by_kappa.items():
        from collections import Counter
        counts = Counter(winners)
        optimal[kappa] = counts.most_common(1)[0][0]

    # Emit Rust source
    print("struct Entry {")
    print("    kappa: u8,")
    print("    n_bits: u8,")
    print("    max_elements: u32,")
    print("    chunk_bits: u8,")
    print("}")
    print()
    print("// Generated by scripts/logup_codegen.py from logup_sweep output.")
    print("// To regenerate: cargo run --release --bin logup_sweep | python3 scripts/logup_codegen.py")
    print("static TABLE: &[Entry] = &[")

    for kappa in sorted(optimal.keys()):
        chunk = optimal[kappa]
        for n_bits in [64, 31]:
            for bucket, label in zip(ELEMENT_BUCKETS, BUCKET_LABELS):
                print(
                    f"    Entry {{ kappa: {kappa}, n_bits: {n_bits}, "
                    f"max_elements: {label}, chunk_bits: {chunk} }},"
                )

    print("];")
    print()
    print("pub fn lookup(kappa: usize, n_bits: usize, estimated_elements: usize) -> usize {")
    print("    for entry in TABLE {")
    print("        if entry.kappa as usize == kappa")
    print("            && entry.n_bits as usize == n_bits")
    print("            && estimated_elements <= entry.max_elements as usize")
    print("        {")
    print("            return entry.chunk_bits as usize;")
    print("        }")
    print("    }")
    print("    super::DEFAULT_LOGUP_CHUNK_BITS")
    print("}")


if __name__ == "__main__":
    main()
